<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;
use RuntimeException;

final class CreatePoliticalStructuresDirectory extends Migration
{
    public function up()
    {
        $this->db->query(<<<'SQL'
CREATE TABLE `political_structures` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `catalog_key` VARCHAR(40) NOT NULL,
    `cep_list_position` SMALLINT UNSIGNED NOT NULL,
    `structure_type` VARCHAR(20) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `acronym` VARCHAR(100) NOT NULL,
    `approval_date` DATE NOT NULL,
    `source_reference` VARCHAR(80) NOT NULL,
    `source_url` VARCHAR(500) NOT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'approved',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_political_structures_catalog_position`
        (`catalog_key`, `cep_list_position`),
    KEY `idx_political_structures_catalog_type`
        (`catalog_key`, `structure_type`, `status`),
    KEY `idx_political_structures_acronym` (`acronym`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
SQL);

        $rows = [
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>1,'structure_type'=>'parti','name'=>'Konkèt pou Konkeri Kiskeya','acronym'=>'KONKET-K2','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>2,'structure_type'=>'parti','name'=>'Réseau Bouclier National','acronym'=>'BOUCLIER','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>3,'structure_type'=>'parti','name'=>'Aksyon pou Konstwi yon Ayiti Oganize','acronym'=>'AKAO','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>4,'structure_type'=>'parti','name'=>"Conviction Patriotique Pour la Restauration d'Haïti",'acronym'=>'CONPRESH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>5,'structure_type'=>'parti','name'=>"Parti Mackandal pour le Progrès d'Haïti",'acronym'=>'PMPH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>6,'structure_type'=>'parti','name'=>'Rasanble','acronym'=>'RASANBLE','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>7,'structure_type'=>'parti','name'=>'Fòs Liberatris pou Ayiti Demen','acronym'=>'FLAD','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>8,'structure_type'=>'parti','name'=>'Mouvement National des Citoyens','acronym'=>'MNC','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>9,'structure_type'=>'parti','name'=>'Parti Populaire National','acronym'=>'PPN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>10,'structure_type'=>'parti','name'=>'Parti Politique Providence','acronym'=>'PROVIDENCE','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>11,'structure_type'=>'parti','name'=>'Pati Politik Pitit Dessalines','acronym'=>'PPPD','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>12,'structure_type'=>'parti','name'=>'Parti Rénovateur Haïtien','acronym'=>'PREH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>13,'structure_type'=>'parti','name'=>'Parti pour le Bien-être des Haïtiens','acronym'=>'PBH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>14,'structure_type'=>'parti','name'=>"Mobilisation pour le Progrès d'Haïti",'acronym'=>'MPH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>15,'structure_type'=>'parti','name'=>'Alternative Socialiste','acronym'=>'ASO','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>16,'structure_type'=>'parti','name'=>'Chanjman Ayiti Natirèlman ak Yahwey','acronym'=>'CHANY','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>17,'structure_type'=>'parti','name'=>'Parti Social Rénové','acronym'=>'PSR','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>18,'structure_type'=>'parti','name'=>'Union des Patriotes Progressistes en Action','acronym'=>'UPPA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>19,'structure_type'=>'parti','name'=>'Mouvement Indépendant pour la Réconciliation Nationale','acronym'=>'MIRN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>20,'structure_type'=>'parti','name'=>'Réveil des Citoyens Haïtiens','acronym'=>'RCH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>21,'structure_type'=>'parti','name'=>'Rassemblement des Patriotes Haïtiens','acronym'=>'RPH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>22,'structure_type'=>'parti','name'=>'Les Engagés pour le Développement','acronym'=>'EDE','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>23,'structure_type'=>'parti','name'=>"Coalition Citoyenne et Humanitaire pour le Développement d'Haïti",'acronym'=>'COACHDHA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>24,'structure_type'=>'parti','name'=>"Parti Révolutionnaire Intégré d'Haïti",'acronym'=>'PRIH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>25,'structure_type'=>'parti','name'=>'Ayisyen pou Ayiti','acronym'=>'S.O','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>26,'structure_type'=>'parti','name'=>'Pacte Coude-à-Coude Inter-Classe et Inter-Génération','acronym'=>'PCC-II','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>27,'structure_type'=>'parti','name'=>'Parti Différence Pour Haïti','acronym'=>'PADHA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>28,'structure_type'=>'parti','name'=>'Parti Nationaliste Haïtien','acronym'=>'PANAH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>29,'structure_type'=>'parti','name'=>'Rasanbleman Nasyonal Fòs Demokratik yo','acronym'=>'RANFO','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>30,'structure_type'=>'parti','name'=>"Réseau pour le Plaidoyer l'Épanouissement et le Progrès",'acronym'=>'REZO-PEP','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>31,'structure_type'=>'parti','name'=>'Parti Démocrate Haïtien','acronym'=>'PADEMH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>32,'structure_type'=>'parti','name'=>"Union Nationale pour l'Intégrité et la Réconciliation",'acronym'=>'UNIR AYITI INI','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>33,'structure_type'=>'parti','name'=>'Pati Politik Peyizan','acronym'=>'PEYIZAN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>34,'structure_type'=>'parti','name'=>'Parti des Révoltés','acronym'=>'PREV','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>35,'structure_type'=>'parti','name'=>'Parti Conscience Nationale','acronym'=>'PCN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>36,'structure_type'=>'parti','name'=>'Résultat Démocratique','acronym'=>'RD','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>37,'structure_type'=>'parti','name'=>'Fòs Chanjman Nasyonal','acronym'=>'FCN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>38,'structure_type'=>'parti','name'=>'Effort et Solidarité pour Construire une Alternative Nationale Populaire','acronym'=>'ESCANP','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>39,'structure_type'=>'parti','name'=>'Palmis','acronym'=>'PALMIS','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>40,'structure_type'=>'parti','name'=>'Parti Réformiste National','acronym'=>'PRN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>41,'structure_type'=>'parti','name'=>'Mouvement Nationaliste Progressiste Haïtien','acronym'=>'MNPH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>42,'structure_type'=>'parti','name'=>'Fòs Pèp La','acronym'=>'FPL','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>43,'structure_type'=>'parti','name'=>'Haïti Devant','acronym'=>'HD','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>44,'structure_type'=>'parti','name'=>'Haïti en Marche pour le Développement','acronym'=>'HAMAD','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>45,'structure_type'=>'parti','name'=>'Ayiti An Aksyon','acronym'=>'AAA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>46,'structure_type'=>'parti','name'=>'Konbit Nasyonal','acronym'=>'KONA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>47,'structure_type'=>'parti','name'=>'Fanmi Lavalas','acronym'=>'FANMI LAVALAS','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>48,'structure_type'=>'parti','name'=>'Fusion des Sociaux-Démocrates Haïtiens','acronym'=>'PFSDH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>49,'structure_type'=>'parti','name'=>'Parti Politique Ekla','acronym'=>'PPE','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>50,'structure_type'=>'parti','name'=>'Rasanbleman Sosyalis pou yon Inisyativ tou Nèf','acronym'=>'RASIN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>51,'structure_type'=>'parti','name'=>'Ansanm Nou Fò','acronym'=>'ANF','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>52,'structure_type'=>'parti','name'=>'Konvansyon pou Refondasyon Nasyon an','acronym'=>'KORE-N','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>53,'structure_type'=>'parti','name'=>"Groupe d'Appui Juvénile pour le changement d'Haïti",'acronym'=>'GAJCH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>54,'structure_type'=>'parti','name'=>'Inisyativ Sitwayen Ayisyen Kap Travay sou Wout yon lòt Ayiti pou Evolisyon ak Anviwònman Nòmal','acronym'=>'SITWAYEN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>55,'structure_type'=>'parti','name'=>'Grand Rassemblement des Citoyens Emancipés','acronym'=>'GRACE','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>56,'structure_type'=>'parti','name'=>'Parti Démocrate-Chrétien Haïtien','acronym'=>'PDCH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>57,'structure_type'=>'parti','name'=>'Rasanbleman Patriyòt Pwogresis Pou Devlopman','acronym'=>'RPPD','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>58,'structure_type'=>'parti','name'=>"Parti Révolutionnaire Pour l'Organisation et le Progrès",'acronym'=>'PROP','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>59,'structure_type'=>'parti','name'=>'Destinée du Peuple Haïtien','acronym'=>'DPH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>60,'structure_type'=>'parti','name'=>'Vision Intégrale pour la Reconstruction Haïtienne','acronym'=>'VIREHA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>61,'structure_type'=>'parti','name'=>'Tèt Ansanm pour le Sauvetage Haïtien','acronym'=>'TASH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>62,'structure_type'=>'parti','name'=>'Lanbi Demokratik pou Chanjman','acronym'=>'LDC','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>63,'structure_type'=>'parti','name'=>'Pati Chimen Limyè','acronym'=>'CHIMEN LIMYE','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>64,'structure_type'=>'parti','name'=>'Parti INITE','acronym'=>'INITE','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>65,'structure_type'=>'parti','name'=>'Parti Héritage des Précurseurs Nationaux','acronym'=>'PHPN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>66,'structure_type'=>'parti','name'=>'Vision-Action-Réalisation','acronym'=>'VAR','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>67,'structure_type'=>'parti','name'=>'Pati Sèvitè Ayisyen','acronym'=>'PSA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>68,'structure_type'=>'parti','name'=>"Force Révolutionnaire d'Entente Nationale",'acronym'=>'FREN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>69,'structure_type'=>'parti','name'=>'Mouvement pour la Reconstruction Nationale','acronym'=>'MRN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>70,'structure_type'=>'parti','name'=>'Pati Kreyòl Nou ye','acronym'=>'P.K.N','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>71,'structure_type'=>'parti','name'=>'Collège National des Démocrates','acronym'=>'CND','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>72,'structure_type'=>'parti','name'=>'Pati Vizyon Dayiti','acronym'=>'PVD','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>73,'structure_type'=>'parti','name'=>'Réveil d’Haïti','acronym'=>'REHA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>74,'structure_type'=>'parti','name'=>'Mouvement Travailliste Haïtien','acronym'=>'MTH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>75,'structure_type'=>'parti','name'=>"Mouvement pour L'Intégration de la Nation au Développement Effectif et Irréversible d'Haïti",'acronym'=>'MINDEFFIHA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>76,'structure_type'=>'parti','name'=>'Konbit Liberasyon Ekonomik','acronym'=>'KLE','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>77,'structure_type'=>'parti','name'=>'Solidarite des Unités Démocratiques Dévouées','acronym'=>'SUDD','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>78,'structure_type'=>'parti','name'=>'Parti Républicain Haïtien','acronym'=>'PRHA HAYITI','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>79,'structure_type'=>'parti','name'=>'Parti de la Restauration et du Changement','acronym'=>'PRC','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>80,'structure_type'=>'parti','name'=>'Entente Nationale','acronym'=>'ENA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>81,'structure_type'=>'parti','name'=>'Parti de la Diaspora Haïtienne pour Haïti','acronym'=>'MUDHAH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>82,'structure_type'=>'parti','name'=>'Organisation du Peuple en Lutte','acronym'=>'OPL','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>83,'structure_type'=>'parti','name'=>"Réseau des Patriotes Intègres pour le Redressement d'Haïti",'acronym'=>'RESPIRE-HAITI','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>84,'structure_type'=>'parti','name'=>'Gwoupman Angaje pou Demokrasi','acronym'=>'GAD','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>85,'structure_type'=>'parti','name'=>'Relève Citoyenne','acronym'=>'RELEC','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>86,'structure_type'=>'parti','name'=>'Parti Unité Reformé','acronym'=>'PUR','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>87,'structure_type'=>'parti','name'=>'Patriyòt Rasanble pou sove Lakay','acronym'=>'PARASOL','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>88,'structure_type'=>'parti','name'=>'Démocrates Visionnaires pour la Nouvelle Haïti','acronym'=>'DVNH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>89,'structure_type'=>'groupement','name'=>'Konbit ak Aksyon Pou Ayiti Bèl','acronym'=>'KAPAB','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>90,'structure_type'=>'groupement','name'=>'Grand Rassemblement National Démocrate','acronym'=>'GRAND','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>91,'structure_type'=>'groupement','name'=>'Platfòm Rekonsilye','acronym'=>'P.R','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>92,'structure_type'=>'groupement','name'=>'Platfòm Politik Gras pou Ayiti','acronym'=>'PPGA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>93,'structure_type'=>'groupement','name'=>'Anfòs pou Sove Lonè','acronym'=>'ANFÒS POU SOVE LONÈ','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>94,'structure_type'=>'groupement','name'=>"Debout Citoyen pour la Transformation d'Haïti",'acronym'=>'DEBOUT CITOYEN','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>95,'structure_type'=>'groupement','name'=>'Myèl','acronym'=>'MYEL','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>96,'structure_type'=>'groupement','name'=>'Debout Patriotes','acronym'=>'DPA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>97,'structure_type'=>'groupement','name'=>'Delivrans','acronym'=>'DELIVRANS','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>98,'structure_type'=>'groupement','name'=>'Ayiti Transfòme','acronym'=>'AYITI TRANSFOME','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>99,'structure_type'=>'groupement','name'=>'En Avant pour Haïti','acronym'=>'EAPH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>100,'structure_type'=>'groupement','name'=>'Debloke','acronym'=>'DEBLOKE','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>101,'structure_type'=>'groupement','name'=>"LAPEH ak Alye'l yo",'acronym'=>'LAPEH','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>102,'structure_type'=>'groupement','name'=>'Viktwa','acronym'=>'VIKTWA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>103,'structure_type'=>'groupement','name'=>'Solidarite pou Ayiti Respire','acronym'=>'SOL AYITI','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>104,'structure_type'=>'groupement','name'=>'Solèy','acronym'=>'SOLEY','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
            ['catalog_key'=>'cep-2026-08-14','cep_list_position'=>105,'structure_type'=>'groupement','name'=>'Coppos-Haïti et Alliés','acronym'=>'CHA','approval_date'=>'2026-08-14','source_reference'=>'CEP/DC/045-2526','source_url'=>'https://cephaiti.ht/wp-content/uploads/2026/08/Liste-definitive-des-structures-politiques-agreees-cep-1.pdf','status'=>'approved'],
        ];

        $this->db->table('political_structures')->insertBatch($rows);

        $count = $this->db
            ->table('political_structures')
            ->where('catalog_key', 'cep-2026-08-14')
            ->countAllResults();

        if ($count !== 105) {
            throw new RuntimeException(
                'The CEP 2026 political structures catalog was not fully inserted.'
            );
        }
    }

    public function down()
    {
        $this->db->query('DROP TABLE IF EXISTS `political_structures`');
    }
}
